default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: root
  password: 123456
  database: api_app_development

test:
  <<: *default
  database: api_app_test

production:
  <<: *default
  database: api_app_production
  username: api_app
  password: <%= ENV['API_CHALLENGE_DATABASE_PASSWORD'] %>
